<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rplidar">

    <xacro:property name="laser_length" value="0.05"/>
    <xacro:property name="laser_radius" value="0.05"/>
    <xacro:property name="update_rate" value="10"/>
    <xacro:property name="visualize" value="true"/>
    <xacro:property name="min_angle" value="-3"/>
    <xacro:property name="max_angle" value="3"/>
    <xacro:property name="min_range" value="0.1"/>
    <xacro:property name="max_range" value="6.0"/>
    <xacro:property name="noise_mean" value="0.00"/>
    <xacro:property name="noise_sttdev" value="0.01"/>

    <!--接口说明(函数变量)
        postion_z   laser底部相对于base平面中心的z方向坐标，建议值大于0，0会报错
        rotation_r  laser底部相对于base平面中心的roll
        rotation_p  laser底部相对于base平面中心的pitch
        rotation_y  laser底部相对于base平面中心的yaw

        接口说明(缺省变量)
        laser_length      laser_link的长度
        visualize         laser的可视化，建议false
        update_rate       laser的频率，建议5.5
        min_angle         激光数据的最小角度，建议-3
        max_angle         激光数据的最大角度，建议3
        min_range         激光数据的最小距离，建议0.1
        max_range         激光数据的最大距离，建议6.0
        noise_mean        激光数据的高斯噪声均值，建议0.0
        noise_sttdev      激光数据的高斯噪声方差，建议0.01
        
        一般需要修改获取到的传感器文件几处地方，parent_link,joint的origin和rpy，传感器插件变量
    -->
    <xacro:macro name="rplidar" params="postion_z
                                        rotation_r 
                                        rotation_p 
                                        rotation_y ">

        <joint name="laser_joint" type="fixed">
            <origin xyz="0 0 ${postion_z/2+laser_length/2}" rpy="${rotation_r} ${rotation_p} ${rotation_y}" />
            <parent link="laser_link"/>
            <child link="laser"/>
        </joint>

        <link name="laser">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                         iyy="0.01" iyz="0.0"
                         izz="0.01" />
            </inertial>

            <visual>
                <origin xyz=" 0 0 0 " rpy="0 0 0" />
                <geometry>
                    <cylinder length="${laser_length}" radius="${laser_radius}"/>
                </geometry>
            </visual>

            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${laser_length}" radius="${laser_radius}"/>
                </geometry>
            </collision>
        </link> 

        <gazebo reference="laser">
            <material>Gazebo/Black</material>
        </gazebo>

        <gazebo reference="laser">
            <sensor type="ray" name="rplidar">
                <pose>0 0 0 0 0 0</pose>
                <visualize>${visualize}</visualize>
                <update_rate>${update_rate}</update_rate>
                <ray>
                    <scan>
                      <horizontal>
                        <samples>360</samples>
                        <resolution>1</resolution>
                        <min_angle>${min_angle}</min_angle>
                        <max_angle>${max_angle}</max_angle>
                      </horizontal>
                    </scan>
                    <range>
                      <min>${min_range}</min>
                      <max>${max_range}</max>
                      <resolution>0.01</resolution>
                    </range>
                    <noise>
                      <type>gaussian</type>
                      <mean>${noise_mean}</mean>
                      <stddev>${noise_sttdev}</stddev>
                    </noise>
                </ray>
                <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
                    <topicName>/scan</topicName>
                    <frameName>laser</frameName>
                </plugin>
            </sensor>
        </gazebo> 

    </xacro:macro>
</robot>
